package com.cctns.apprehend.core.domain.apprehend;

import com.cctns.apprehend.core.domain.CommonParamsDomain;
import com.cctns.apprehend.core.domain.accused.AliasJsonDomain;
import com.cctns.apprehend.core.domain.acts.ActSectionDomain;
import jakarta.persistence.Column;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class ApprehendMemoDomain extends CommonParamsDomain {

    private Long apprehendSrno;
    private Long id;
    private Integer psCd;
    private Long juvenileVid;
    private Long accusedVid;
    private Long juvenileSrno;
    private Long firJuvenileSrno;
//    private Long juvenileSrnoMigr;
    private Integer regSrno;
    private Integer apprehendYear;
    private Long firRegNum;
    private Boolean isFromGd;
    private String gdNum;
    private LocalDateTime gtDt;
    private Integer apprehendTypeCd;
    private LocalDateTime apprehendDt;
    private String apprehendAlphanum;
    private String firstName;
    private String middleName;
    private String lastName;
    private String firstNameEng;
    private String middleNameEng;
    private String lastNameEng;
    private Boolean isReArrested;
    private Long reApprehendSrno;
    private Integer relationTypeCd;
    private String relativeName;
    private String relativeNameEng;
    private String relativeAlias;
    private Long relMobileNum;
    private String relTelephone;
    private Integer othrRelTypeCd;
    private String othrRelName;
    private String othrRelNameEng;
    private Long othrRelMobileNum;
    private Integer religionCd;
    private Integer nationalIdTypeCd;
    private Integer genderCd;
    private Integer categoryCd;
    private String[] eduQualCd;
    private Integer livingStatusCd;
    private Integer maritalStatusCd;
    private Integer occupationCd;
    private Integer ageProofTypeCd;
    private Integer langDialectCd;
    private Integer ageTypeCd;
    private Integer ageYrs;
    private Integer ageMnths;
    private Integer yob;
    private LocalDate dob;
    private Integer ageFromYrs;
    private Integer ageToYrs;
    private Boolean isAgeProofReq;
    private Long mobileNum;
    private String telephone;
    private String email;
    private Integer nationalityCd;
    private Integer languageDialectCd;
    private String othIdentificationMarks;
    private Integer bloodGroupCd;
    private Integer incomeGroupCd;
    private String heightFromCm;
    private String heightToCm;
    private Integer weightKg;
    private String eprisonPid;
    private String apprehendByOthers;
    private String apprehendByPisCd;
    private Long apprFromStateId;
    private Long apprFromDistrictId;
    private Long apprFromPsId;
    private String apprFromState;
    private String apprFromDistrict;
    private String apprFromPs;
    private Integer apprehendBeatCd;
    private Integer apprehendActionTakenCd;
    private String custodyActionOther;
    private Integer apprehendStatusCd;
    private String courtOrderDetails;
    private Boolean isApprehendPhotoTaken;
    private Boolean belongToCrimeGang;
    private Integer criminalGangCd;
    private String injuryDetails;
    private Boolean isMedExamReq;
    private String apprehendReason;
    private String ioCd;
    private Boolean isRelatIntimated;
    private Integer intimateRelTypeCd;
    private String intimateRelType;
    private String intimateRelName;
    private LocalDateTime intimateDt;
    private String intimationGivenTo;
    private Integer intimateModeCd;
    private Boolean isIntMobVerif;
    private Long intimateMobNum;
    private String intimateModeDetail;
    private String intimationRemarks;
    private Boolean isApprGrndComm;
    private Long presIntRelAddrMigr;
    private Long permIntRelAddrMigr;
    private Boolean isFpTaken;
    private Boolean isFpChance;
    private Boolean isDangerous;
    private Boolean isJuvenileDisable;
    private Integer physicalCondCd;
    private Boolean hasPrevJumpBail;
    private String prevJumpBailDetails;
    private Boolean isGenerallyArmed;
    private Boolean operatesWithAccomplish;
    private Boolean isKnownCriminal;
    private String knownCriminalDetails;
    private Boolean isRecidivist;
    private Boolean likelyJumpsBail;
    private Boolean afterBailCommitsCrime;
    private Boolean wantedOtherCase;
    private String wantedCaseDetails;
    private String prevConvictionDetail;
    private Long presentAddress1CdMigr;
    private Long presentAddress2CdMigr;
    private Long presentAddress3CdMigr;
    private Long permanentAddressCdMigr;
    private LocalDateTime psIntimateDt;
    private Boolean isPhotoTaken;
    private Boolean isApprPermTaken;
    private Boolean isInfoVerified;
    private String courtEstblCd;
    private String courtName;
    private Integer evidenceTypeCd;
    private Integer idTypeCd;
    private Boolean isProclaimedOffender;
    private Boolean isDressForMF;
    private String otherLivingStatus;
    private String apprehendPlace;
    private String otherOccupation;
    private String anyOtherDetails;
    private String firCopyGivenTo;
    private String offenderDetails;
    private String apprehendCircumstances;
    private Integer custodyTypeCd;
    private String custodyTypeName;
    private String jcwoName;
    private Long jcwoParentMobileNum;
    private String jcwoParentAddress;
    private String intimatePostAddr;
    private String nameRnkWlfOfcr;
    private String ciclGdNum;
    private LocalDateTime ciclGdDt;


   private List<AliasJsonDomain> aliases;

    private Long accusedSrno;
    private Long existingAccSrno;
    private Long existingAccFirRegNum;
    private Long nextSeqNo;
    private Long currentSeqNo;
    private Boolean isNew;
    private Boolean isExistingAccused;

    private String psName;
    private String districtName;
    private String stateName;
    private String ps;
    private String district;
    private String state;
    private String firDisplayNum;
    private String gdDisplayNum;
    private String ciclGdDisplayNum;
    private String firRegDt;

    private String recordStatus;
    private LocalDateTime recordCreatedOn;
    private Long recordCreatedBy;
//    private LocalDateTime recordUpdatedOn;
//    private Long recordUpdatedBy;
//    private String recordSyncFrom;
//    private LocalDateTime recordSyncOn;

    //One To Many Relation
    private List<ApprehendAddressDomain> apprehendAddress;
    private List<ApprehendWitnessDomain> apprehendWitness;
    private List<ApprehendIntimateAddrDomain> intimateAddress;
    private List<ApprehendFilesDomain> fileList;
    private List<ActSectionDomain> actSectionList;
    private List<ApprehendNationalIdDomain> idList;
}

